name: Run Backend Jest Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      - name: show folders
        run: dir

      - name: Install dependencies
        working-directory: /home/runner/work/recipe_book/backend
        run: npm install

      - name: Run Jest tests
        working-directory: /backend
        run: jest --runInBand
