name: Run Backend Jest Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Install jest
        working-directory: backend
        run: npm install jest

      - name: Run Jest tests
        working-directory: backend
        run: jest --runInBand
