name: Run All Jest Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --install-strategy=shallow
        
      - name: Run backend Jest tests
        run: npm test --workspace recipe-backend
        
      - name: Run functionality Jest tests
        run: npm test --workspace recipe-book-functionality
