name: Run All Jest Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        working-directory: backend
        run: npm install
        
      - name: Run backend Jest tests
        working-directory: backend
        run: npm test

      - name: Install functionality dependencies
        working-directory: functionality
        run: npm install
        
      - name: Run functionality Jest tests
        working-directory: functionality
        run: npm test

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python tests
        working-directory: backend/python_scripts/pdf_scraper_testing
        run: |
          python -m unittest discover -s test
